apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-identity-service-config
  namespace: healthcare
data:
  SPRING_PROFILES_ACTIVE: "production"
  SERVER_PORT: "8080"
  LOG_LEVEL: "INFO"
  APP_LOG_LEVEL: "INFO"
  
  # Database Configuration (non-sensitive)
  DB_POOL_MAX_SIZE: "20"
  DB_POOL_MIN_IDLE: "10"
  DB_CONNECTION_TIMEOUT: "30000"
  
  # Redis Configuration (non-sensitive)
  REDIS_DATABASE: "0"
  REDIS_TIMEOUT: "2000ms"
  REDIS_SSL_ENABLED: "true"
  
  # Kafka Configuration (non-sensitive)
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "PLAIN"
  KAFKA_CONSUMER_GROUP_ID: "healthcare-identity-service"
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  
  # Auth0 Configuration (non-sensitive)
  AUTH0_CONNECTION: "Username-Password-Authentication"
  AUTH0_SCOPE: "openid profile email"
  
  # Cloud Provider
  CLOUD_PROVIDER: "azure"
  CLOUD_REGION: "eastus"
  
  # Monitoring
  TRACING_ENABLED: "true"
  TRACING_SAMPLING_RATE: "0.1"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: healthcare-identity-service-secrets
  namespace: healthcare
type: Opaque
stringData:
  # Database Credentials - Injected by Infrastructure
  DATABASE_URL: "jdbc:postgresql://postgres.healthcare.svc.cluster.local:5432/identity_db"
  DATABASE_USER: "identity_user"
  DATABASE_PASSWORD: "INJECTED_BY_INFRASTRUCTURE"
  
  # Redis Credentials - Injected by Infrastructure
  REDIS_HOST: "redis-master.healthcare.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "INJECTED_BY_INFRASTRUCTURE"
  
  # Kafka Credentials - Injected by Infrastructure
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-0.kafka.svc.cluster.local:9092,kafka-broker-1.kafka.svc.cluster.local:9092"
  KAFKA_USERNAME: "identity-service"
  KAFKA_PASSWORD: "INJECTED_BY_INFRASTRUCTURE"
  
  # Auth0 Credentials - Injected by Infrastructure
  AUTH0_DOMAIN: "healthcare-prod.auth0.com"
  AUTH0_CLIENT_ID: "INJECTED_BY_INFRASTRUCTURE"
  AUTH0_CLIENT_SECRET: "INJECTED_BY_INFRASTRUCTURE"
  AUTH0_AUDIENCE: "https://api.healthcare.com"
  
  # FHIR Server Credentials - Injected by Infrastructure
  FHIR_SERVER_URL: "https://fhir.healthcare.com/r4"
  FHIR_USERNAME: "identity-service"
  FHIR_PASSWORD: "INJECTED_BY_INFRASTRUCTURE"
  
  # Azure KeyVault (if using)
  AZURE_KEYVAULT_URI: "https://healthcare-kv.vault.azure.net/"
  AZURE_CLIENT_ID: "INJECTED_BY_INFRASTRUCTURE"
  AZURE_CLIENT_SECRET: "INJECTED_BY_INFRASTRUCTURE"
  AZURE_TENANT_ID: "INJECTED_BY_INFRASTRUCTURE"