# Default/Development Profile Configuration
# This profile is for local development with minimal external dependencies

spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: IdentityServiceHikariCP
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: false
        use_sql_comments: true
        jdbc:
          batch_size: 20
    show-sql: false
    open-in-view: false
  
  liquibase:
    enabled: false # Using Hibernate DDL for development
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  # Security - simplified for development
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
  
  # Redis - optional for development
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      connect-timeout: 5s
      lettuce:
        pool:
          enabled: false # Disable pooling for development
  
  # Kafka - optional for development
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 0
    consumer:
      group-id: ${spring.application.name}-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    admin:
      fail-fast: false # Don't fail if Kafka is not available

# Auth0 Configuration - Mock/Test values for development
auth0:
  domain: ${AUTH0_DOMAIN:dev.auth0.com}
  clientId: ${AUTH0_CLIENT_ID:dev-client-id}
  clientSecret: ${AUTH0_CLIENT_SECRET:dev-client-secret}
  audience: ${AUTH0_AUDIENCE:https://dev-api}
  enabled: false # Disable Auth0 for local development

# FHIR Configuration - Mock for development
fhir:
  server:
    url: ${FHIR_SERVER_URL:http://localhost:8080/fhir}
    enabled: false

# Development-specific settings
development:
  mock-external-services: true
  enable-debug-endpoints: true
  bypass-authentication: true
  seed-data: true # Load sample data on startup

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE